### ISSUE TITLE
Debug completo del progetto

### ISSUE THREAD

**Issue by danielegenta** [danielegenta/ProjectTPSI#1]
Richiesta:Controllare se, cliccando una qualunque combinazione, lo script 'impazzisce' facendo cose non previste.
Come:Fare un po' di prove (partite)
Cosa controllare:Testo celle, testo conta-mosse, testo timer.

**Comment by samuele96** [comment]
tutto bene

**Comment by danielegenta** [comment]
Fai debug e dammi un feedback se trovi qualche errore specificando in che condizioni e in che cosa consiste.

**Comment by Themite** [comment]
Non so se è molto giusto quello che sto per dire, ma ho fatto una serie di prove e in pratica quando giochi,magari per sbaglio clicchi "mescola" il gioco si inceppa e non si riesce a fare nuova partita perchè la "X" sparisce e un numero a caso viene doppio ogni click.
Tutto torna normale quando si aggiorna la pagina.

**Comment by Themite** [comment]
Secondo me si dovrebbe togliere il bottone "X" perchè giocando molto spesso ci si confonde. Secondo me lasciando una cella vuota (colore bianco oppure come preferisci te) non ci si confonderebbe cosi tanto.

**Comment by Themite** [comment]
Ah ancora una cosa il bottone "Pausa" secondo me quando si viene cliccato dovrebbe non solo fermare il tempo trascorso, ma anche il gioco in modo da non poter fare nessuna azione finche non verrà schiacciato dinuovo, perchè se dopo si continua a giocare il bottone rimane su riavvia, schiacciandolo rimane comunque su riavvia e avanti cosi.

**Comment by Themite** [comment]
Voi cosa ne pensate del click sui bottoni? Secondo me è un po pesante,cioè quando un bottone viene schiacciato non esegue la operazione immediatamente ma dopo un pò.

**Comment by danielegenta** [comment]
Allora grazie per tutte le segnalazioni, ti rispondo una per una.
1. Penso che questo errore sia presente solo su una vecchia release, prova a scaricare quella più recente (l'ultima caricata mi pare sia la 0.8v1), fammi sapere se persiste.
2.Si, ci avevo pensato, lo avevo messo tanto per comodità mentre sviluppavamo inizialmente.
3.Ottimo, non lo avevo notato! Provvedo/iamo a correggere.
4.Non lo noto sinceramente, prova a usare Chrome e usare l'ultima release del gioco.

Dato che abbiamo aggiunto un po' di cose (mescola, nuova ecc) vi ri-invito (tu e Levrone) a fare debug in quanto più si aggiungono cose più c'è la possibilità di errori, tenetemi aggiornato!

Ps. e piccolo OT : Levrone prendi esempio da Mite!
