### ISSUE TITLE
Feedback grafica

### ISSUE THREAD

**Issue by danielegenta** [danielegenta/ProjectTPSI#2]
Cosa ne dite della grafica? vi piace, non vi piace? perché? cosa cambiereste? come cambiereste?
Sbizzarritevi.

**Comment by samuele96** [comment]
Secondo me i bottoni con le righe non vanno bene...le righe in mezzo ti fanno incrociare gli occhi, secondo me uno a tinta unita è più semplice e si capisce di più...la semplicità è la base di tutto.

**Comment by danielegenta** [comment]
-Per quanto riguarda le righe sono d'accordo (dopo/domani cerco altre texture) comunque sono div NON bottoni.
-Non scrivere 'ahahha' è una cosa seria!

**Comment by samuele96** [comment]
Ok.

**Comment by Themite** [comment]
Per quanto riguarda la grafica è veramente bella. Dalla foto le righe con le strisce sembravano brutte, ma giocandoci secondo me ci stanno di brutto.

**Comment by danielegenta** [comment]
Approfitto della issue aperta per esprimere una mia idea: mettere un paio di bottoni o un cmb nel quale scegliere fra magari 2/3 grafiche (minimal, dark e magari una terza), che ne dite? ci sta?
