### ISSUE TITLE
Texture per div

### ISSUE THREAD

**Issue by danielegenta** [danielegenta/ProjectTPSI#3]
Cosa: cercare texture per div (se preferite tinta unita il codice esadecimale, altrimenti il link tutorial).
Requisiti: permettere agevolmente la lettura dei numeri, abbinarsi bene al contesto (preferibilmente scura) e facilmente riproducibile tramite CSS (No immagini).

**Comment by Themite** [comment]
Ho trovato alcuni siti con dei css carini che ti possono piacere e facili da usare 
1)http://tutorialzine.com/2013/10/12-awesome-css3-features-you-can-finally-use/
2)http://www.colorzilla.com/gradient-editor/  ===> con questo invece puoi facilmente crearti uno stile che piace a te oppure che vuoi abbinare al contesto generandoti automaticamente il css.
3)http://www.1stwebdesigner.com/programming/mastering-css-gradients-in-less-than-1-hour/ ===> invece qua la il 5° background mi piace davvero un casino. Penso che piacere anche a te Genta!.

**Comment by danielegenta** [comment]
I primi due siti li avevo già visti per quanto riguarda il terzo: carino! Direi di chiedere anche agli altri due se gli piace di più quello che quello che c'è ora (background dark)!

**Comment by Themite** [comment]
1)http://mudcu.be/bg/#{"width":1440,"height":799,"config":{"textureEnabled":true,"alpha":0.75,"scale":1,"seed":11899,"grayscale":true,"rotate":0},"gradient":{"0":"#000000","1":"#000000","0.10000000000000002":"#b4b7a5","0.20000000000000004":"#a66300","0.3000000000000001":"#bbc1a1","0.4000000000000001":"#aa7a00","0.5":"#000000","0.6":"#dfa000","0.7":"#bcc691","0.7999999999999999":"#c59300","0.9":"#bcc691"}}

**Comment by Themite** [comment]
background: ##000000;
